---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.15
inputs:
  - name: pcf-pipelines
  - name: terraform-state
  - name: credhub-cli-tarball
params:
    FOUNDATION_NAME:
    CONCOURSE_CREDHUB_SECRET:
    CONCOURSE_CREDHUB_CA_CERT:


run:
  path: pcf-pipelines/install-pcf/aws/tasks/update-credhub/task.sh
